# Generated by Django 6.0.6 on 2026-08-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_delete_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
