# Generated by Django 6.0.6 on 2026-07-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('budget', 'Budget'), ('saving', 'Saving'), ('reminder', 'Reminder'), ('report', 'Report')], default='reminder', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notification', max_length=100),
            preserve_default=False,
        ),
    ]
