# Generated by Django 6.0.6 on 2026-08-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('budget', 'Budget'), ('expense', 'Expense'), ('saving', 'Saving'), ('reminder', 'Reminder'), ('report', 'Report'), ('weekly_summary', 'Weekly Summary')], default='reminder', max_length=20),
        ),
    ]
