# Generated by Django 6.0.6 on 2026-07-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavingsGoal',
        ),
    ]
