# Generated by Django 6.0.6 on 2026-08-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_alter_budget_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='warning_100_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='warning_80_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='warning_90_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='warning_exceeded_sent',
            field=models.BooleanField(default=False),
        ),
    ]
