# Generated by Django 6.0.6 on 2026-07-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_remove_report_user_expense_income_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
    ]
