# Generated by Django 6.0.6 on 2026-07-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_savingsgoal_created_at_savingsgoal_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingsgoal',
            old_name='deadline',
            new_name='target_date',
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='status',
            field=models.CharField(default='In Progress', max_length=20),
        ),
    ]
