# Generated by Django 6.0.6 on 2026-08-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_rename_deadline_savingsgoal_target_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsgoal',
            name='saved_amount',
        ),
    ]
