# Generated by Django 6.0.6 on 2026-07-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_rename_date_income_income_date_income_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='title',
        ),
    ]
